### ISSUE TITLE
My matrix is more of a snake pattern but the software isn't working with it

### ISSUE THREAD

**Issue by Boaztheostrich** [TylerTimoJ/LMCSHD#9]
In some of the videos you had much pixel order options, are those available anywhere?

**Comment by Boaztheostrich** [comment]
I figured it out, it is hard to understand though, the version shown in the videos makes a lot more sense to me.

**Comment by 3dart22** [comment]
help!  how and where to insert the exported gif animation code in the sketch?  I have not found detailed instructions anywhere for using the ready-made code from the LMCS HD program Please give me an answer!  or give a link where to download a ready-made sketch with a code for displaying on an RGB LED FAST LED MATRIX OR AT LEAST A SCREEN OF HOW IT SHOULD LOOK!  copy code paste void loop in parentheses !  and nothing works .. before inserting the code into the loop, I delete ewent and still the matrix does not glow ...
